name: audio-class-1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.2.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - audioread=2.1.9
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.3.1
  - freetype=2.10.4
  - gettext=0.21.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=68.1
  - idna=2.10
  - importlib-metadata=4.5.0
  - intel-openmp=2021.2.0
  - ipykernel=5.5.5
  - ipython=7.24.1
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.8.0
  - jupyterlab=3.0.16
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.0
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.1
  - libllvm10=10.0.1
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - librosa=0.8.1
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.41.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - ninja=1.10.2
  - notebook=6.4.0
  - numba=0.53.1
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.14.0.2
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - pooch=1.4.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.19
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.9.0
  - pytz=2021.1
  - pyzmq=22.1.0
  - readline=8.1
  - requests=2.25.1
  - resampy=0.2.2
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - send2trash=1.7.1
  - setuptools=52.0.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.35.5
  - tensorboardx=2.2
  - terminado=0.10.1
  - testpath=0.5.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tornado=6.1
  - tqdm=4.61.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - urllib3=1.26.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.36.2
  - x264=1!161.3030
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - lmdb==1.2.1
    - torchsummary==1.5.1
